name: Update Discord Status

on:
  schedule:
    - cron: '*/5 * * * *' # Actualiza cada 5 minutos (ajusta según sea necesario)

jobs:
  update-discord-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set Discord Status
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          curl -X PATCH -H "Content-Type: application/json" -H "Authorization: Bot $DISCORD_TOKEN" -d '{"custom_status":{"text":"🎶 Escuchando YouTube"}}' https://discord.com/api/v9/users/@me/settings

